<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class UpdateItemRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            "name" => "required|unique:items,name,".$this->route('item')->id."|min:3|max:50",
            "category_id" => "required",
            "price"=>"required",
            "description"=>"nullable|max:100",
            "photo" => "nullable|file|mimes:jpeg,png|max:5000"
        ];
    }

    public function failedValidation(Validator $validator)
    {
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
        throw new \HttpRequestException(response()->json([
            'success'   => false,

            'message'   => 'Validation errors',

            'data'      => $validator->errors()
        ]));
    }

    public function messages()

    {

        return [

            'name.required' => 'Title is required',

            'body.required' => 'Body is required'

        ];

    }
}
